// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNY5KIXO4qOTOm8oQJfoiNYGqj8KjVec',
    appId: '1:660974095967:web:c3089f01bf7ef1da4f95ea',
    messagingSenderId: '660974095967',
    projectId: 'fitnesspro-d7171',
    authDomain: 'fitnesspro-d7171.firebaseapp.com',
    storageBucket: 'fitnesspro-d7171.firebasestorage.app',
    measurementId: 'G-LVY7QYYV3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBETjOifTVakfctk9xxKJGC6bzdhFJBxVQ',
    appId: '1:660974095967:android:78233cfb6f0623e74f95ea',
    messagingSenderId: '660974095967',
    projectId: 'fitnesspro-d7171',
    storageBucket: 'fitnesspro-d7171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-q31j_xziro0sLLVStRMj3jaxlHM-3w',
    appId: '1:660974095967:ios:4fd14be48fac0a634f95ea',
    messagingSenderId: '660974095967',
    projectId: 'fitnesspro-d7171',
    storageBucket: 'fitnesspro-d7171.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ-q31j_xziro0sLLVStRMj3jaxlHM-3w',
    appId: '1:660974095967:ios:4fd14be48fac0a634f95ea',
    messagingSenderId: '660974095967',
    projectId: 'fitnesspro-d7171',
    storageBucket: 'fitnesspro-d7171.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvNY5KIXO4qOTOm8oQJfoiNYGqj8KjVec',
    appId: '1:660974095967:web:cd66f5cfd98de9414f95ea',
    messagingSenderId: '660974095967',
    projectId: 'fitnesspro-d7171',
    authDomain: 'fitnesspro-d7171.firebaseapp.com',
    storageBucket: 'fitnesspro-d7171.firebasestorage.app',
    measurementId: 'G-VM9NNKMLB3',
  );
}
